spring.application.name=smart-clinic-management-system
spring.datasource.url=jdbc:mysql://localhost:3306/smart_clinic
spring.datasource.username=root
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
security.jwt.secret=smartclinicsecretkeysmartclinicsecretkey12345
